# This is as dockerfile to run it in your machine (not heroku)

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /application

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everythink else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source
COPY --from=build /application/out .
ENTRYPOINT [ "dotnet", "MinimalApi_SendSlackMessage.dll" ]